title                  = "Pokhari.com"
baseurl                = "https://pokhari.github.io"
relativeurls           = true
builddrafts            = false
canonifyurls           = true
contentdir             = "content"
languageCode           = "en-US"
layoutdir              = "layouts"
publishdir             = "public"
author                 = "Raju Rimal"
pygmentsuseclasses     = true
disqusshortname        = "therimalaya"
pluralizelisttitles    = false
googleAnalytics        = ""
ignoreFiles            = ["\\.Rmd$", "_files$", "_cache$"]
theme                  = "cocoa"

[permalinks]
fixed                  = ":title/"
blog                   = "blog/:slug/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = ''
weight                 = -1000
identifier             = "home"
icon                   = 'fa-home'
url                    = "/"
pre                    = '<i class ="fa fa-home" aria-hidden ="true"></i>'

[[menu.main]]
name                   = "Links"
weight                 = -111
identifier             = "links"
url                    = "/links/"

[params]
latestpostscount       = 10    # how many posts to display on the home page
i18n_flags             = false # whether to display small country flags for available translations
author                 = "pokhari.com"
cachebuster            = true  # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Light and Shades of Life"
email                  = "pokhari.com@gmail.com"
extracssfiles          = [ "/css/override.css", "/css/font-awesome.min.css" ] # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/therimalaya"
highlightjs            = true
lang                   = "en"
linkedin               = "//linkedin.com/in/therimalaya"
noshowreadtime         = false                      # if true, don't show "<x> minutes read" in posts
selfintro              = "light and shades of life" # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/tweetpokhari"
# highlightjslanguages = ["go"]                               # additional languages not included in the "common" set
# avatar               = "img/profile.png"                    # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
gravatar               = "95ee48194519b91267b4c6ecf0e5f884" # do not use in the same time as avatar
